alabaster==0.7.16
astropy==6.0.1
astropy-iers-data==0.2024.3.25.0.29.50
asttokens==2.4.1
babel==2.16.0
certifi==2024.2.2
charset-normalizer==3.4.0
comm==0.2.2
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
dionpy==1.2.1
docutils==0.17.1
echaim==1.1.3
executing==2.0.1
ffmpeg-progress-yield==0.7.9
fonttools==4.50.0
fortranformat==2.0.0
h5py==3.12.1
healpy==1.17.3
idna==3.10
imagesize==1.4.1
iniconfig==2.0.0
ipykernel==6.29.3
ipython==8.22.2
iricore==1.9.0
it==1.0.0
jedi==0.19.1
Jinja2==3.1.4
jplephem==2.21
jupyter_client==8.6.1
jupyter_core==5.7.2
kiwisolver==1.4.5
latexcodec==3.0.0
llvmlite==0.42.0
MarkupSafe==3.0.2
matplotlib==3.8.3
matplotlib-inline==0.1.6
nest-asyncio==1.6.0
numba==0.59.1
numpy==1.26.4
packaging==24.0
pandas==2.2.2
parso==0.8.3
pbio==0.0.2
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
pluggy==1.5.0
prompt-toolkit==3.0.43
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pybtex==0.24.0
pybtex-docutils==1.0.3
pyerfa==2.0.1.1
Pygments==2.17.2
pymap3d==3.1.0
pyparsing==3.1.2
pytest==8.3.2
python-dateutil==2.9.0.post0
pytz==2023.4
PyYAML==6.0.1
pyzmq==25.1.2
requests==2.32.3
scipy==1.12.0
seaborn==0.13.2
sgp4==2.23
six==1.16.0
skyfield==1.48
snowballstemmer==2.2.0
Sphinx==5.3.0
sphinx-autodoc-typehints==1.23.0
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-bibtex==2.6.3
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
stack-data==0.6.3
toml==0.10.2
tornado==6.4
tqdm==4.66.6
traitlets==5.14.2
tzdata==2024.1
urllib3==2.2.3
wcwidth==0.2.13
